import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"

const features = [["The Hot-Key Problem", "An autonomous agent with a hot private key can spend whatever the key controls. A compromised dependency or bad model output can turn one agent into a treasury-draining machine.", "UNBOUNDED ACCESS"], ["The Swarm Problem", "Parent and child agents need strict isolation. Without it, a compromised worker can consume capital intended for other agents or continue spending through recursive execution.", "CASCADING RISK"], ["The Settlement Problem", "When one agent hires another, payment needs a release condition. KYA moves that settlement condition on-chain through verifiable delivery proofs.", "TRUSTLESS DELIVERY"]]

export default function FeaturesSection() { return <>
  <section id="features" className="mx-auto max-w-6xl px-4 py-16"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-semibold uppercase tracking-widest text-rose-600">The problem</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-zinc-950 sm:text-4xl">Autonomous agents can execute transactions.<br /><span className="text-slate-500">They were never designed to safely control unrestricted capital.</span></h2><p className="mt-5 text-slate-600">Modern agents can monitor markets, rebalance positions, execute trades, hire other agents, and manage financial workflows. Most systems still give them a private key with access to real money. KYA introduces an enforcement layer between the agent and the treasury.</p></div><div className="mt-10 grid gap-4 md:grid-cols-3">{features.map(([title, desc, label]) => <Card key={title} className="rounded-2xl border-slate-200 bg-white shadow-sm"><CardHeader><p className="text-xs font-semibold tracking-widest text-rose-600">{label}</p><CardTitle className="mt-2 text-zinc-950">{title}</CardTitle></CardHeader><CardContent className="text-sm leading-relaxed text-slate-600">{desc}</CardContent></Card>)}</div></section>
  <section className="border-y border-slate-800 bg-slate-950 px-4 py-20 text-center text-white"><h2 className="text-3xl font-semibold tracking-tight sm:text-4xl">KYA turns unrestricted agent wallets into contained financial actors.</h2><p className="mx-auto mt-4 max-w-2xl text-slate-400">Every agent gets exactly the capital, permissions, and spending authority it has been granted. Nothing more.</p></section>
  <section id="protocol" className="bg-slate-50 px-4 py-16"><div className="mx-auto max-w-6xl"><div className="mx-auto max-w-2xl text-center"><p className="text-sm font-semibold uppercase tracking-widest text-rose-600">The enforcement layer</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-zinc-950">Capital, policies, and settlement in one enforcement layer.</h2><p className="mt-3 text-slate-600">KYA combines programmable authorization with capital isolation and proof-based settlement so agents can operate against real financial systems without unrestricted treasury access.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2">{[["Bounded Capital", "Every agent operates inside a defined capital boundary. Funds are isolated through a hierarchical mandate tree.", "idle + childGranted + jobLocked = granted"], ["USD-Denominated Policies", "Define limits in human-readable financial terms. FTSOv2 pricing keeps policies expressed in USD across supported assets.", "Max spend per call: $50 · Max spend per day: $500"], ["Conditional Escrow", "Funds enter an escrow flow with a defined release condition: FUNDED → LOCKED → DELIVERY VERIFIED → RELEASED.", "Capital is released only when the configured condition is satisfied."], ["Proof-Based Settlement", "Flare Data Connector proofs verify external events and transactions before releasing escrowed funds.", "XRPL Payment · EVM Transaction · External Delivery Proof"]].map(([title,desc,highlight]) => <Card key={title} className="rounded-2xl border-slate-200 bg-white shadow-sm"><CardHeader><CardTitle className="text-zinc-950">{title}</CardTitle></CardHeader><CardContent><p className="text-sm leading-relaxed text-slate-600">{desc}</p><p className="mt-5 rounded-lg border border-rose-100 bg-rose-50/50 p-3 font-mono text-xs text-rose-950">{highlight}</p></CardContent></Card>)}</div></div></section>
</> }
